### create a new patient entity
POST http://localhost:4000/patients/createPatient
Content-Type: application/json



{
  "name": "PANKAJ KUMAR",
  "email": "SINGH@GMAIL.COM",
  "address": "hyderabad",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

//{
//  "name": "John doe",
//  "email": "john12@gmail.com",
//  "address": "hyderabad",
//  "dateOfBirth": "1995-09-09",
//  "registeredDate": "2024-11-28"
//}

###